
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "http://www.enkirche.fr"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

baseurl: /

# Google tracking id

google-tracking-id: "<UA-316171-11>"

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: True

#############
# HTML Head #
#############

lang: "fr"
author: "Emmanuel Enkirche"
title: "{ Emmanuel Enkirche }"
description: "Blog et website de Emmanuel Enkirche. Quelques notes sur ma recherche professionnelle en générale, ma formation TSMEL en particulier. Les opinions exprimées sont les miennes."
keywords: "enkirche, emmanuel, logisticien, CV"
favicon: "/img/favicon.ico"

################
# Header layout #
################

black-favicon: "/img/black-lab-glass.ico"

background-img: "../img/intro-bg.jpg"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: True # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 5000
lines: # You can add HTML Tags in the Text
  - text: "The lower you fall, the higher you'll fly."
  - text: "Where’s your will to be weird?"

me-img: "/img/jetpacktocat.png"

##############################
# Color the browser elements #
##############################
color-browser: "#000000"
apple-status-bar-style: "black"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

enable-gesture-navigation: True

post-preview-words: 96

paginate: 5

email-share: True
fb-share: False
twitter-share: False
linkedin-share: True
reddit-share: False
google-plus-share: True
tumblr-share: False
pinterest-share: False
pocket-share: False
vkontakte-share: False

disqus-shortname: "manubarnum"

syntax-highlight: True

############
# Timeline #
############

events:
  - image: "/img/career/spidertocat.png"
    date: "Mars 2013 - Aujourd'hui"
    description: "Employé logistique pour la SAS Cocagne"
  - image: "/img/career/baracktocat.jpg"
    date: "Janvier 2000 - Mars 2013"
    description: "Intérimaire"

# First image of the Timeline

timeline-img: "/img/timeline/default.png"

###########
# Contact #
###########

email: "contact@enkirche.fr"

################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
author_blurb: "De nature entreprenante, je souhaite évoluer vers un poste avec plus d’enjeux, aussi j’ai décidé de suivre une formation de technicien supérieur en méthode et exploitation logistique (TSMEL) du vendredi 30 septembre jusqu’au 30 juin 2017 au centre AFTRAL de St Etienne du Rouvray. Mes capacités d’analyse et de travail en autonomie seront des atouts en vue de la réussite de ce projet."
author_blurb_image: "/img/author.png"

##################
# Social Buttons #
##################

social:
  - title: "linkedin"
    url: "https://linkedin.com/in/emmanuelenkirche"
  - title: "google-plus"
    url: "https://plus.google.com/107898723162758678646"
  - title: "github"
    url: "https://github.com/manubarnum"
  - title: "rss"
    url: "/feed.xml"

############
# 404 page #
############

404-img: "/img/labtocat.png"

##################
# GPG on Keybase #
##################

keybase-username: manubarnum
keybase-in-social: False
keybase-in-footer: False

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  About: 'about'
  Blog: 'latest-post'
  Timeline: 'timeline'
  Contact: 'contact'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
  - jemoji
