
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "http://www.enkirche.fr"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

baseurl: ''

# Google tracking id

google-tracking-id: "<UA-316171-11>"

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: True

#############
# HTML Head #
#############

lang: "fr"
author: "Emmanuel Enkirche"
title: "{ Emmanuel Enkirche }"
description: "Blog et website de Emmanuel Enkirche. Quelques notes sur ma recherche professionnelle en générale, ma formation TSMEL en particulier. Les opinions exprimées sont les miennes."
keywords: "enkirche, emmanuel, logisticien, CV"
favicon: "/img/point-favicon.ico"

################
# Header layout #
################

black-favicon: "/img/point-favicon.ico"

background-img: "../img/fonddecran.jpg"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: True # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 5000
lines: # You can add HTML Tags in the Text
  - text: "Bienvenue sur mon CV en ligne!"
  - text: "Quelques notes sur ma recherche professionnelle."

me-img: "/img/portrait.png"

##############################
# Color the browser elements #
##############################
color-browser: "#000000"
apple-status-bar-style: "black"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/point-36p.png"
icon-48p: "/img/web-app/point-48p.png"
icon-72p: "/img/web-app/point-72p.png"
icon-96p: "/img/web-app/point-96p.png"
icon-144p: "/img/web-app/point-144p.png"
icon-192p: "/img/web-app/point-192p.png"

########
# Blog #
########

enable-gesture-navigation: True

post-preview-words: 96

paginate: 5

email-share: True
fb-share: False
twitter-share: False
linkedin-share: True
reddit-share: False
google-plus-share: True
tumblr-share: False
pinterest-share: False
pocket-share: False
vkontakte-share: False

disqus-shortname: "Emmanuel Enkirche"

syntax-highlight: True

############
# Timeline #
############

events:
  - image: "/img/timeline/aftral.png"
    date: "Septembre 2016- en cours"
    description: "Etudiant en logistique à l'AFTRAL"
  - image: "/img/timeline/cocagne.png"
    date: "Mars 2013 - en pause"
    description: "Employé logistique pour la SAS Cocagne"
  - image: "/img/timeline/sika.png"
    date: "Janvier 2012 - Octobre 2012"
    description: "Opérateur cariste pour SIKA "
  - image: "/img/timeline/imerys.png"
    date: "Novembre 2011 - Decembre 2011"
    description: "Approvisonneur Cariste pour Imerys"
  - image: "/img/timeline/autoliv.png"
    date: "Mars 2010 - Octobre 2011"
    description: "Approvisonneur Cariste pour Autoliv"
  - image: "/img/timeline/paulstra.png"
    date: "Avril - Juillet 2009"
    description: "Approvisonneur Cariste pour Paulstra"
  - image: "/img/timeline/autoliv.png"
    date: "Janvier 2007 - Juillet 2008"
    description: "Approvisonneur Cariste pour Autoliv"
  - image: "/img/timeline/afpa.png"
    date: "Juin 2005 - Juin 2006"
    description: "Assistant en Bureatique et Informatique pour l'AFPA"
  - image: "/img/timeline/cesi.png"
    date: "Septembre 2004 - Juin 2005"
    description: "Etudiant Analyse Programmation au CESI"  
  - image: "/img/timeline/dumonchel.png"
    date: "Février - Avril 2004"
    description: "Chauffeur VL pour Dumonchel"
  - image: "/img/timeline/autoliv.png"
    date: "Janvier 2001 - Juillet 2003"
    description: "Opérateur de production pour Autoliv"
  - image: "/img/timeline/superu.png"
    date: "2000"
    description: "Employé commercial pour Super U"  
  - image: "/img/timeline/grisel.png"
    date: "Septembre 1995 - Décembre 1999"
    description: "Chauffeur de bus pour Grisel"
  - image: "/img/timeline/23bima.png"
    date: "Avril 1993 - Mars 1995"
    description: "Volontaire Service Long Outre-Mer au Sénégal"

# First image of the Timeline

timeline-img: "/img/timeline/defaut.png"

###########
# Contact #
###########

email: "emmanuel@enkirche.fr"

################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
author_blurb: ""
author_blurb_image: ""

##################
# Social Buttons #
##################

social:
  - title: "linkedin"
    url: "https://linkedin.com/in/emmanuelenkirche"
  - title: "google-plus"
    url: "https://plus.google.com/107898723162758678646"
  - title: "github"
    url: "https://github.com/manubarnum"
  - title: "rss"
    url: "/feed.xml"

############
# 404 page #
############

404-img: "/img/labtocat.png"

##################
# GPG on Keybase #
##################

keybase-username: manubarnum
keybase-in-social: False
keybase-in-footer: False

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  About: 'about'
  Blog: 'latest-post'
  Timeline: 'timeline'
  Contact: 'contact'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
  - jemoji
